#include "precompiled.h"
#include "rehlds_tests_shared.h"
#include "cppunitlite/TestHarness.h"

// The bug: COM_Parse ends a bare token at the first space.
TEST(SpacedPathTokenizing, Download, 1000)
{
	EngineInitializer engInitGuard;

	char cmdbuf[512];

	Q_strlcpy(cmdbuf, "dlfile models/my models/model.mdl");
	Cmd_TokenizeString(cmdbuf);

	ZSTR_EQUAL("argv(1) should be truncated at the space", "models/my", Cmd_Argv(1));
	ZSTR_EQUAL("args() should keep the whole path", "models/my models/model.mdl", Cmd_Args());
}

#ifdef REHLDS_FIXES
TEST(SpacedPathReconstruct, Download, 1000)
{
	EngineInitializer engInitGuard;

	struct testdata_t {
		const char *cmd;
		const char *expected;
	};

	testdata_t testdata[] = {
		// unchanged without whitespace
		{ "dlfile models/model.mdl", "models/model.mdl" },

		// the reported bug
		{ "dlfile models/my models/model.mdl", "models/my models/model.mdl" },
		{ "dlfile sound/cool song.wav", "sound/cool song.wav" },

		// runs are preserved, not collapsed
		{ "dlfile sound/a  b.wav", "sound/a  b.wav" },
		{ "dlfile sound/a\tb.wav", "sound/a\tb.wav" },

		// COM_Parse breaks out ()'{}, as single-character tokens
		{ "dlfile models/momoko/fangzi (3).mdl", "models/momoko/fangzi (3).mdl" },
		{ "dlfile models/a,b.mdl", "models/a,b.mdl" },
		{ "dlfile models/it's {ok}.mdl", "models/it's {ok}.mdl" },

		// already complete in argv(1)
		{ "dlfile \"sound/cool song.wav\"", "sound/cool song.wav" },

		// a client-embedded newline must not leak in
		{ "dlfile sound/cool song.wav\nkick", "sound/cool song.wav" },

		// trailing whitespace is trimmed
		{ "dlfile sound/cool song.wav   ", "sound/cool song.wav" },

		// customizations are untouched
		{ "dlfile !MD50123456789abcdef0123456789abcdef", "!MD50123456789abcdef0123456789abcdef" },
	};

	for (int i = 0; i < ARRAYSIZE(testdata); i++)
	{
		testdata_t *d = &testdata[i];
		char cmdbuf[512];
		char namebuf[MAX_PATH];

		Q_strlcpy(cmdbuf, d->cmd);
		Cmd_TokenizeString(cmdbuf);

		const char *name = SV_GetRequestedDownloadName(namebuf, sizeof(namebuf));
		CHECK("Download name should not be rejected", name != NULL);
		ZSTR_EQUAL("Wrong reconstructed download name", d->expected, name);
	}
}

// A whole .res line is one resource path, punctuation included.
TEST(ResourceLineTrim, Download, 1000)
{
	struct testdata_t {
		const char *line;
		const char *expected;	// NULL => line holds no resource
	};

	testdata_t testdata[] = {
		{ "models/model.mdl", "models/model.mdl" },

		// what COM_Parse used to shatter
		{ "models/momoko/fangzi (3).mdl", "models/momoko/fangzi (3).mdl" },
		{ "sound/cool song.wav", "sound/cool song.wav" },

		// whitespace, and CR from CRLF endings
		{ "  models/model.mdl", "models/model.mdl" },
		{ "models/model.mdl   ", "models/model.mdl" },
		{ "\tmodels/a b.mdl\t\r", "models/a b.mdl" },

		// quoted paths
		{ "\"models/a b.mdl\"", "models/a b.mdl" },

		// COM_Parse skipped comments for free
		{ "// generated by ResGen", NULL },
		{ "   // indented comment", NULL },
		{ "", NULL },
		{ "   \t  ", NULL },

		// trailing comments too
		{ "models/model.mdl // keep this", "models/model.mdl" },
		{ "models/a b.mdl\t// tab before comment", "models/a b.mdl" },
		{ "\"models/a b.mdl\" // quoted, then a comment", "models/a b.mdl" },

		// ...but only at a token boundary
		{ "models//foo.mdl", "models//foo.mdl" },
		{ "models//foo.mdl // and a real comment", "models//foo.mdl" },
	};

	for (int i = 0; i < ARRAYSIZE(testdata); i++)
	{
		testdata_t *d = &testdata[i];
		char linebuf[512];

		Q_strlcpy(linebuf, d->line);
		char *res = SV_TrimResourceLine(linebuf);

		if (!d->expected)
		{
			CHECK("Line should not yield a resource", res == NULL);
			continue;
		}

		CHECK("Line should yield a resource", res != NULL);
		ZSTR_EQUAL("Wrong trimmed resource line", d->expected, res);
	}
}

// Reject rather than truncate into some other file's name.
TEST(OverlongPathRejected, Download, 1000)
{
	EngineInitializer engInitGuard;

	char cmdbuf[512];
	char namebuf[64];

	Q_strlcpy(cmdbuf, "dlfile ");

	int prefix = Q_strlen(cmdbuf);
	for (int i = 0; i < 100; i++)
		cmdbuf[prefix + i] = 'a';
	cmdbuf[prefix + 100] = '\0';

	Cmd_TokenizeString(cmdbuf);

	CHECK("Overlong download name should be rejected",
		SV_GetRequestedDownloadName(namebuf, sizeof(namebuf)) == NULL);
}
#endif // REHLDS_FIXES
